# Site settings
title: Prototope
email: email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Prototope is a project of <a href="http://www.khanacademy.org/">Khan Academy</a>.
  <br /><a href="https://vine.co/v/M2UBYqeqzD6">vroom vroom</a>.
baseurl: "/Prototope" # the subpath of your site, e.g. /blog/
url: "http://khan.github.io" # the base hostname & protocol for your site

## Uncomment these lines if we ever want to be social
twitter_username: khanacademy
github_username:  khan
exclude:
  - vendor
  - dash
  - dendoc.py
  - readme.md
  - requirements.txt
  - env

# Build settings
markdown: kramdown

collections:
  methods:
    output: false
    layout: api

  docs:
    output: true
    permalink: /api_docs/:path/

defaults:
  -
    scope:
      path: ""
      type: "methods"
    values:
      layout: "api"
