# Site settings
title: How To Prototope
email: email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Everything you ever wanted to know about prototpe but were
  too afraid to ask.
baseurl: "/Prototope" # the subpath of your site, e.g. /blog/
url: "http://khan.github.io" # the base hostname & protocol for your site

## Uncomment these lines if we ever want to be social
# twitter_username: nsfmc
# github_username:  nsfmc
exclude: [vendor]

# Build settings
markdown: kramdown

collections:
  methods:
    output: false
    layout: api

  docs:
    output: true
    permalink: /api_docs/:path/

defaults:
  -
    scope:
      path: ""
      type: "methods"
    values:
      layout: "api"
